@startuml BlueLinesSequenceDiagram

skinparam Shadowing false

database "SQL_DB" order 4
actor "User"

group User Selects Search / Explore
User -> UI: Select Search / Explore
UI -> User: Load corresponding UI Elements
end

group Process for Searching for Location
User -> UI: Search for a location
UI -> Backend: Search Query
Backend -> SQL_DB: Query Location Conditions
SQL_DB -> Backend: Return Location Conditions
Backend -> UI: Return Location Query Resultsbu
UI -> User: Return Location Search Results
end

loop Loop until area selected then search area as location
User -> UI: Navigate around map
UI -> Backend: Query USGS Data For New Area
Backend -> SQL_DB: Query Location Data
SQL_DB -> Backend: Return Location Conditions
Backend -> UI: Return Query Results
UI -> User: Return Search Results
end

@enduml